name: Update Submodules

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true  # Ensure submodules are cloned
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Submodules
        run: |
          git submodule update --remote --merge
          git commit -am "Automated update of submodules"
          git push origin main
